# Generated by Django 2.2.6 on 2020-03-28 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noviwebshopapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='image',
            field=models.ImageField(upload_to='paintings'),
        ),
        migrations.AlterField(
            model_name='painting',
            name='rented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renter_painting', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='painting',
            name='rented_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='rented_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
