# Generated by Django 2.2.6 on 2020-03-16 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noviwebshopapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
                ('url', models.URLField(unique=True)),
                ('Painting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noviwebshopapp.Painting')),
            ],
        ),
        migrations.CreateModel(
            name='AccesRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noviwebshopapp.Webpage')),
            ],
        ),
    ]
