# Generated by Django 2.2.6 on 2020-03-16 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noviwebshopapp', '0002_accesrecord_webpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesrecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 16, 22, 7, 27, 960128)),
        ),
    ]
