# Generated by Django 2.2.6 on 2020-03-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noviwebshopapp', '0002_auto_20200328_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='role',
            field=models.CharField(choices=[('teacher', 'Leraar'), ('student', 'Student')], max_length=25),
        ),
    ]
