# Generated by Django 3.0.3 on 2020-06-19 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noviwebshopapp', '0003_auto_20200328_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField(auto_now=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('painting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_painting', to='noviwebshopapp.Painting')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_painting', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
