# Generated by Django 2.2.6 on 2020-03-17 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noviwebshopapp', '0003_accesrecord_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='painting',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2020, 3, 17, 15, 11, 45, 356880)),
        ),
        migrations.AlterField(
            model_name='accesrecord',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 17, 15, 11, 45, 357877)),
        ),
    ]
