# Generated by Django 3.0.3 on 2020-06-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noviwebshopapp', '0004_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='painting',
            new_name='painting_id',
        ),
    ]
