# Generated by Django 3.0.3 on 2020-06-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noviwebshopapp', '0005_auto_20200619_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='painting_id',
            new_name='painting',
        ),
        migrations.RenameField(
            model_name='painting',
            old_name='painting_id',
            new_name='painting',
        ),
    ]
