# Generated by Django 3.0.3 on 2020-06-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noviwebshopapp', '0006_auto_20200619_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='Order-test', max_length=50),
        ),
    ]
